export const GET_SHOWS_START = 'GET_SHOWS_START';
export const GET_SHOW_START = 'GET_SHOW_START';
export const GET_PORTAL_START = 'GET_PORTAL_START';
export const GET_SHOW_BY_GENRE_START = 'GET_SHOW_BY_GENRE_START';